Repository metwork-framework/mfcom, pull requests merged in 2018-11, with the labels that each got.

#41 fix: rollback on plugin packaging around virtualenv
  adm/_install_plugin_virtualenv
Labels: Status: Pending

#47 fix: raise some timeouts for timeout problems on slow machines
  adm/_circus.status
Labels: Merge Now, Status: Review Needed

#50 fix: fix incomplete plugins removal (in some cases)
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Merge Now, Status: Review Needed

#53 feat: add a no-input option
  adm/bootstrap_plugin.py
Labels: Merge Now, Status: Pending

#56 feat: better plugin management (with errors in pre/post scripts)
  adm/Makefile
  adm/_plugins.postuninstall
  adm/_plugins.preuninstall
  adm/bootstrap_plugin.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Merge Now, Status: Pending

#59 build: remove _plugins.postuninstall
  adm/Makefile
  adm/_plugins.postuninstall
Labels: Merge Now, Status: Review Needed

#62 Npmsupport
  adm/plugin.mk
Labels: Merge Now, Status: Review Needed

#64 fix: fix missing postinstall scripts
  adm/Makefile
  adm/_plugins.postinstall
Labels: Merge Now, Status: Pending

#65 fix: fix crontab exception in a basic docker container
  adm/_make_and_install_crontab.sh
  adm/_uninstall_crontab.sh
Labels: Status: Review Needed

#67 feat: Add a "plugin succesfully created message"
  adm/bootstrap_plugin.py
Labels: Status: Review Needed
