Repository metwork-framework/mfcom, pull requests merged in 2018-10, with the labels that each got.

#13 Update .mergify.yml
  .mergify.yml
Labels: in progress

#23 chore: use conditional downstream custom image
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#24 chore: fix last commit
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#26 chore: package createrepo is now in build image
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#27 feat: better cleaning during make clean inside a plugin
  adm/plugin.mk
Labels: Status: Review Needed

#29 feat: better plugin build
  adm/_install_plugin_virtualenv
  adm/plugin.mk
Labels: Status: Review Needed

#32 feat: better plugin cleaning (again)
  adm/plugin.mk
Labels: Status: Review Needed
