Repository metwork-framework/mfcom, pull requests merged in 2019-05, with the labels that each got.

#130 docs: Update MFCOM documentation
  .gitignore
  doc/Makefile
  doc/_static/css/override_theme.css
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.rst
  doc/circus_hooks.rst
  doc/conf.py
  doc/conf_monitor.rst
  doc/images/logo-metwork.png
  doc/images/metwork.ico
  doc/index.rst
  doc/mfutil.md
  doc/mfutil.rst
  doc/todo.rst
  layer_custom.md
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/0100_mfutil/mfutil/cli.py
  layers/layer1_python3/0100_mfutil/mfutil/layerapi2.py
  layers/layer1_python3/0100_mfutil/mfutil/net.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/layer_custom.md
  layers/layer9_default/layer_custom.md
  layers/layer9_python/layer_custom.md
Labels: Status: Review Needed

#133 fix: fix an automatic reload issue in some corner cases
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
Labels: Merge Now, Status: Review Needed

#134 fix: fix typo
  doc/conf.py
Labels: Status: Review Needed

#136 Docfix
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
Labels: Merge Now

#135 Fixsystem
  adm/metwork
  config/Makefile
  config/sysctl_metwork.conf
Labels: Status: Review Needed

#137 Plugin names
  adm/_install_plugin_virtualenv
  adm/_make_crontab.sh
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
  layers/layer1_python3/0100_mfutil/fastentrypoints.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_info.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_list.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Merge Now, Status: Review Needed

#140 Update MFCOM documentation
  doc/Makefile
  doc/mfutil.rst
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/documented_utilities
  layers/layer1_python3/layer_custom.md
Labels: Merge Now, Status: Review Needed

#141 build: remove python layer
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
  layers/layer9_python/layer_custom.md
Labels: Merge Now, Status: Closed

#142 Conf monitor stuff
  adm/_plugins.postinstall
  adm/plugin_wrapper
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
  layers/layer1_python3/0300_conf_monitor/setup.py
Labels: Merge Now, Status: Review Needed, backport-to-0.6

#145 docs: Update MFCOM documentation
  doc/circus_hooks.rst
  doc/conf_monitor.rst
Labels: Status: Review Needed

#146 docs: Update MFCOM documentation
  .gitignore
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/conf.py
  doc/index.rst
  doc/mfcom_intro.md
Labels: Status: Review Needed

#147 build: fix mflog addon
  layers/layer1_python3/0500_mflog_addon/mflog_metwork_addon/__init__.py
Labels: Merge Now, Status: Review Needed

#144 (manual) backport of #142 in release_0.6 branch
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
  layers/layer1_python3/0300_conf_monitor/setup.py
Labels: Merge Now, Status: Review Needed

#148 build: mflog addon fix
  layers/layer1_python3/0500_mflog_addon/mflog_metwork_addon/__init__.py
Labels: Merge Now

#149 docs: Put introduction at the beginning
  doc/index.rst
Labels: Status: Review Needed

#150 build: fix gitignore
  .gitignore
Labels: Merge Now

#151 build: remove devtools optional dependency
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#152 feat: jsonlog2elasticsearch is classified as monitoring process
  adm/telegraf_collector_metwork_module.py
Labels: Status: Review Needed, backport-to-0.7

#154 feat: use envtpl new option --reduce-multi-blank-lines
  adm/_make_circus_conf
  adm/_make_crontab.sh
  adm/_make_nginx_conf
  adm/before_start_redis
  adm/before_start_telegraf
  doc/Makefile
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Status: Review Needed
