Repository metwork-framework/mfcom, pull requests merged in 2019-06, with the labels that each got.

#155 fix: fix conf_monitor issues in random cases
  config/mflog_override.conf
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
Labels: Status: Review Needed, backport-to-0.6, backport-to-0.7

#158 docs: generate automatically changelogs entries in changelogs.rst file
  .gitignore
  doc/Makefile
  doc/changelogs.tmpl
Labels: Status: Review Needed

#160 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed

#161 fix: uninstall plugin if installation failed
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Status: Review Needed, backport-to-0.7

#163 Better stop
  adm/_circus_wait_watcher_stopped.sh
  synutil_c/Makefile
  synutil_c/_synutil.h
  synutil_c/is_interactive.c
  synutil_c/synutil.h
Labels: Merge Now, Status: Review Needed, backport-to-0.7
