Repository metwork-framework/mfcom, pull requests merged in 2019-08, with the labels that each got.

#170 build: new buildcache
  .drone.yml
  Makefile
  adm/startup_scripts_profiles.mk
Labels: Merge Now

#171 feat: move synutil_c and synutil_lua to mfext
  .gitignore
  Makefile
  layers/layer1_python3/0100_mfutil/mfutil/cli.py
  synutil_c/Makefile
  synutil_c/_synutil.h
  synutil_c/echo_bold.c
  synutil_c/echo_clean.c
  synutil_c/echo_nok.c
  synutil_c/echo_ok.c
  synutil_c/echo_running.c
  synutil_c/echo_warning.c
  synutil_c/get_unique_hexa_identifier.c
  synutil_c/is_interactive.c
  synutil_c/synutil.c
  synutil_c/synutil.h
  synutil_c/synutil.pc.pc
  synutil_lua/Makefile
  synutil_lua/synutil.lua
Labels: Merge Now, Status: Review Needed

#172 FIX spelling mistake
  adm/bootstrap_plugin.py
Labels: Status: Review Needed

#174 feat: better conf_monitor handling
  adm/Makefile
  adm/before_start_conf_monitor
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
Labels: Merge Now, Status: Review Needed

#176 feat: layerapi2 is now in a dedicated repository
  adm/plugin.mk
  adm/plugin_wrapper
  bootstrap.sh
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0100_mfutil/tests/test_plugins.py
Labels: Status: Revision Needed

#177 New bootstrap
  bootstrap.sh
  doc/Makefile
Labels: Merge Now, Status: Revision Needed
