Repository metwork-framework/mfcom, pull requests merged in 2019-09, with the labels that each got.

#178 build: better doc
  .gitignore
  .metwork-framework/README.md
  .metwork-framework/components.md
  doc/Makefile
  doc/circus_hooks.rst
  doc/components.md
  doc/components.rst
  doc/conf.py
  doc/index.rst
  doc/layer_root_custom.md
  doc/layers.rst
  doc/mfcom_intro.md
  doc/mfutil.rst
  doc/todo.rst
  documented_utilities
  layer_custom.md
  layers/layer1_python2/documented_utilities
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/documented_utilities
  layers/layer1_python3/layer_custom.md
Labels: Merge Now, Status: Review Needed

#180 feat: replace MODULE* environment variables names by MFMODULE* (MODUL…
  .metwork-framework/configure_a_metwork_package.md
  Makefile
  adm/_circus.reload
  adm/_circus.start
  adm/_circus.status
  adm/_circus.stop
  adm/_circus_schedule_stop_watcher.sh
  adm/_circus_wait_watcher_stopped.sh
  adm/_install_or_update_configured_plugins.py
  adm/_make_and_install_crontab.sh
  adm/_make_circus_conf
  adm/_make_crontab.sh
  adm/_make_nginx_conf
  adm/_nginx.reload
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
  adm/_prepare_config.py
  adm/_uninstall_crontab.sh
  adm/before_start_conf_monitor
  adm/before_start_nginx
  adm/before_start_redis
  adm/before_start_telegraf
  adm/bootstrap_plugin.py
  adm/circus_status_watcher.sh
  adm/config_subdir.mk
  adm/find_zombies_nginx_workers.py
  adm/list_metwork_processes.py
  adm/nginx.status
  adm/plugin.mk
  adm/plugin_wrapper
  adm/redis_status.sh
  adm/startup_scripts_profiles.mk
  adm/telegraf_collector_metwork_module.py
  bootstrap.sh
  doc/mfutil.rst
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_info.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_init.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_list.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_uninstall.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0100_mfutil/tests/test_plugins.py
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
  layers/layer1_python3/0400_jsonlog2elasticsearch_metwork_addon/jsonlog2elasticsearch_metwork_addon/__init__.py
  layers/layer1_python3/0500_mflog_addon/mflog_metwork_addon/__init__.py
Labels: Merge Now, Status: Revision Needed

#182 fix: fix to ensure compatibily with existing plugins using old variab…
  adm/plugin_wrapper
Labels: Merge Now, Status: Review Needed

#183 build: improve backward compatibility for MODULE => MFMODULE transition
  adm/_make_and_install_crontab.sh
  adm/_make_crontab.sh
Labels: Merge Now

#185 fix: fix some issues with node plugins
  adm/_install_plugin_virtualenv
  adm/plugin.mk
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#187 build: fix latest merge on release_0.8 branch
  adm/plugin.mk
Labels: Merge Now, Status: Review Needed
