Repository metwork-framework/mfcom, pull requests merged in 2019-01, with the labels that each got.

#84 [WIP] feat: introduce new autorestart plugin
  .gitignore
  adm/Makefile
  adm/plugin.mk
  adm/plugin_autorestart_excludes
  adm/plugin_autorestart_includes
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer1_python3/0500_extra_python_packages/Makefile
  layers/layer1_python3/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/prerequirements3.txt
  layers/layer1_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Pending, Status: Review Needed

#70 [WIP] feat: refactor node plugins build
  adm/_install_plugin_virtualenv
  adm/plugin.mk
Labels: Merge Now, Status: Pending, Status: Review Needed

#75 [WIP] Resources issue23bis
  Makefile
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
  layers/layer1_python3/0100_mfutil/fastentrypoints.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_info.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_list.py
  layers/layer1_python3/0100_mfutil/mfutil/layerapi2.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
  layers/layer1_python3/0100_mfutil/tests/data/test_build_plugin/.layerapi2_label
  layers/layer1_python3/0100_mfutil/tests/test_plugins.py
  layers/layer1_python3/0200_mflog/fastentrypoints.py
Labels: Merge Now, Status: Pending

#85 feat: add home to plugins.list --json output
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_list.py
Labels: Merge Now, Status: Pending

#86 build: remove old circus autorestart plugin
  layers/layer1_python3/0400_circus_autorestart/Makefile
  layers/layer1_python3/0400_circus_autorestart/Makefile.mk
  layers/layer1_python3/0400_circus_autorestart/circus_autorestart/__init__.py
  layers/layer1_python3/0400_circus_autorestart/setup.py
Labels: Merge Now, Status: Review Needed

#87 build: move circus_autorestart_plugin to mfext
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer1_python3/0500_extra_python_packages/Makefile
  layers/layer1_python3/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/prerequirements3.txt
  layers/layer1_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Pending

#88 Nodefix
  adm/_install_plugin_virtualenv
  adm/_plugins.postinstall
  adm/plugin.mk
Labels: Merge Now, Status: Pending

#89 feat: run post_installation plugins tasks
  adm/_plugins.postinstall
Labels: Status: Review Needed

#92 feat: add _nginx.reload utility
  adm/Makefile
  adm/_nginx.reload
Labels: Status: Review Needed

#90 [WIP] refactor: better node plugin build
  adm/plugin.mk
Labels: Merge Now, Status: Pending

#95 refactor: move conf_monitor logic from mfserv to mfcom
  Makefile
  layers/layer1_python3/0300_conf_monitor/Makefile
  layers/layer1_python3/0300_conf_monitor/Makefile.mk
  layers/layer1_python3/0300_conf_monitor/conf_monitor/__init__.py
  layers/layer1_python3/0300_conf_monitor/setup.py
Labels: Merge Now, Status: Review Needed

#99 make develop more robust
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Status: Review Needed

#98 feat: add a way to display some warnings during plugin installation
  adm/Makefile
  adm/_plugins.is_dangerous
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer1_python3/0100_mfutil/mfutil/cli_tools/plugins_install.py
  layers/layer1_python3/0100_mfutil/mfutil/plugins.py
Labels: Merge Now, Status: Pending
